casestudy_md3/routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\OrderdetailController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HomeUsersController;
use App\Http\Controllers\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('admin1', function () {
    return view('homeadmin');
});
Route::prefix('admin')->group(function () {
    Route::resource('users', UserController::class);
    Route::get('users/search', [UserController::class, 'search'])->name('users.search');

    Route::resource('products', ProductController::class);
    Route::get('products/search', [ProductController::class, 'search'])->name('products.search');

    Route::resource('categories', CategoryController::class);
    Route::get('categories/search', [CategoryController::class, 'search'])->name('categories.search');

    Route::resource('orders', OrderController::class);
    Route::get('orders/search', [OrderController::class, 'search'])->name('orders.search');

    Route::resource('orderdetails', OrderdetailController::class);
    Route::get('orderdetails/search', [OrderdetailController::class, 'search'])->name('orderdetails.search');

   
   
});


Route::prefix('/home')->group(function () {


    Route::get('/home', [HomeController::class, 'home'])->name('home');
    Route::get('/login', [HomeController::class, 'login'])->name('home.login');
    Route::get('/web', [HomeController::class, 'web'])->name('home.web');
    Route::post('/handlelogin', [HomeController::class, 'handlelogin'])->name('home.handlelogin');
    Route::get('/register', [HomeController::class, 'register'])->name('home.register');
    Route::post('/handleRegister', [HomeController::class, 'handleRegister'])->name('home.handleRegister');
    Route::get('/category/{id}', [HomeController::class, 'category'])->name('category');
    Route::get('/detail/{id}', [HomeController::class, 'detail'])->name('detail');
    Route::get('/cart', [HomeController::class, 'cart'])->name('cart');
    Route::post('/addToCart/{id}', [HomeController::class, 'addToCart'])->name('addToCart');
    Route::get('/delete/{id}', [HomeController::class, 'delete'])->name('delete');
});

Route::prefix('/homeUsers')->group(function () {
    Route::get('/category/{id}', [HomeUsersController::class, 'category'])->name('homeUsers.category');
    Route::get('/detail/{id}', [HomeUsersController::class, 'detail'])->name('homeUsers.detail');
    Route::get('/cart', [HomeUsersController::class, 'cart'])->name('homeUsers.cart');
    Route::get('/index', [HomeUsersController::class, 'index'])->name('index');
    Route::post('/addToCartUser/{id}', [HomeUsersController::class, 'addToCartUser'])->name('addToCartUser');
    Route::get('/deleteUser/{id}', [HomeUsersController::class, 'deleteUser'])->name('deleteUser');
});

casestudy_md3/app/Http/Controllers/Admin/OrderdetailController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\OrderdetailsRequest;
use App\Models\OrderdetailModel;
use App\Models\OrderModel;
use App\Models\ProductModel;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class OrderdetailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->search;
        
        // mục tìm kiếm 
        if ($search) {
            $orderdetails = OrderdetailModel::where('orders_id','like','%'.$search.'%')->paginate(5);
        } else {
            $orderdetails = OrderdetailModel::orderBy('orders_id','asc')->paginate(5);
        }
        $params = [
            'orderdetails' => $orderdetails
        ];  
        // echo '<pre>';
        // print_r($orderdetails);
        // echo '</pre>';
        return view('admin.orderdetails.index', $params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $orders     = OrderModel::all();
        $products   = ProductModel::all();
        $params     = [
            'orders'    => $orders,
            'products'  => $products,
        ];
        return view('admin.orderdetails.create' ,$params );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderdetailsRequest $request)
    {
        $orderdetails                 = new OrderdetailModel();
        // dd($orderdetails);
        $orderdetails->orders_id      = $request->orders_id;
        $orderdetails->products_id    = $request->products_id;
        $orderdetails->quantity       = $request->quantity;
        $orderdetails->price          = $request->price;
        $orderdetails->save();
        Session::flash('success', 'Tạo mới khách hàng thành công');
        //tao moi xong quay ve trang danh sach khach hang
        return redirect()->route('orderdetails.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $orderdetails = OrderdetailModel::find($id);
        return view('admin.orderdetails.show', compact('orderdetails'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $orderdetails   = OrderdetailModel::find($id);
        $orders         = OrderModel::all();
        $products       = ProductModel::all();
        $params = [
            'orderdetails'  => $orderdetails,
            'orders'        => $orders,
            'products'      => $products
        ];
        return view('admin.orderdetails.edit' , $params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrderdetailsRequest $request, $id)
    {
        OrderdetailModel::find($id)->update($request->only('orders_id','products_id','quantity','price'));
        return redirect()->route('orderdetails.index')->with('success', 'Cập nhật thành công.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            OrderdetailModel::find($id)->delete();
           }
       catch(Exception $e)
           {
               Session::flash('errors','Xóa không thành công');
               return back()->withError('Xóa không thành công')->withInput();
           }
        // OrderdetailModel::find($id)->delete();
        return redirect()->route('orderdetails.index')->with('success', 'Xóa thành công');
    }
}

casestudy_md3/resources/views/admin/orderdetails/create.blade.php
@extends('layouts.admin')
@section('content')

<form method="post" action='{{ route("orderdetails.store") }}'>
    @csrf
    <h1 class="text-center">Thêm Chi Tiết Đơn Hàng </h1>
    <div class="container">

        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Tên Người Mua </label>
            <select name="orders_id" class="form-control">
                @foreach($orders as $order)
                <option value="{{ $order->id }}"> {{ $order->user->name }} </option>
                @endforeach
            </select>
            @if ($errors)
            <div class="text-danger">{{$errors->first('orders_id')}}</div>
            @endif
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Tên Sản Phẩm </label>
            <select name="products_id" class="form-control">
                @foreach($products as $product)
                <option value="{{ $product->id }}"> {{ $product->name }} </option>
                @endforeach
            </select>
            @if ($errors)
            <div class="text-danger">{{$errors->first('products_id')}}</div>
            @endif
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Số Lượng</label>
            <input type="number" class="form-control" id="exampleInputEmail1" name="quantity">
            @if ($errors)
            <div class="text-danger">{{$errors->first('quantity')}}</div>
            @endif
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Giá Tiền</label>
            <input type="number" class="form-control" id="exampleInputEmail1" name="price">
            @if ($errors)
            <div class="text-danger">{{$errors->first('price')}}</div>
            @endif
        </div>
        <button type="submit" class="btn btn-primary"><i class="fas fa-user-plus"></i> Thêm</button>
        <a type="submit" class="btn btn-dark" href="{{ route('orderdetails.index') }}"><i class="fas fa-backward"></i> Trở lại</a>
    </div>
</form>

@endsection

casestudy_md3/resources/views/admin/orderdetails/edit.blade.php
@extends('layouts.admin')
@section('content')


<h1 class="text-center">Chỉnh Sửa Chi Tiết Đơn Hàng </h1>
<div class="container">
    <form method="post" action='{{ route("orderdetails.update", $orderdetails->id) }}'>
        @csrf
        @method('put')
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Tên Người Mua </label>
            <select name="orders_id" value='{{ $orderdetails->orders_id }}' class="form-control">
                @foreach($orders as $order)
                <option value="{{ $order->id }}"> {{ $order->user->name }} </option>
                @endforeach
            </select>
            @if ($errors)
            <div class="text-danger">{{$errors->first('orders_id')}}</div>
            @endif
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Tên Sản Phẩm </label>
            <select name="products_id" value='{{ $orderdetails->products_id }}' class="form-control">
                @foreach($products as $product)
                <option value="{{ $product->id }}"> {{ $product->name }} </option>
                @endforeach
            </select>
            @if ($errors)
            <div class="text-danger">{{$errors->first('products_id')}}</div>
            @endif
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Số Lượng</label>
            <input type="number" class="form-control" id="exampleInputEmail1" name="quantity" value='{{$orderdetails->quantity}}'>
            @if ($errors)
            <div class="text-danger">{{$errors->first('quantity')}}</div>
            @endif
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Giá Tiền</label>
            <input type="number" class="form-control" id="exampleInputEmail1" name="price" value='{{$orderdetails->price}}'>
            @if ($errors)
            <div class="text-danger">{{$errors->first('price')}}</div>
            @endif
        </div>
        <button type="submit" class="btn btn-primary"><i class="fas fa-pencil-alt"></i>  Chỉnh Sửa </button>
        <a type="submit" class="btn btn-dark" href="{{ route('orderdetails.index') }}"><i class="fas fa-backward"></i> Trở lại</a>
</div>
</form>

@endsection

casestudy_md3/resources/views/admin/orderdetails/index.blade.php
@extends('layouts.admin')

@section('content')
<h1 class="text-center"> Chi Tiết Đơn Hàng </h1>

<a class="btn btn-success" href="{{route('orderdetails.create')}}"><i class="fas fa-folder-plus"></i>Thêm</a>
@if (Session::has('success'))
<p class="text-success">
  <i class="fa fa-check" aria-hidden="true"></i>{{ Session::get('success') }}
</p>
@endif
@if (Session::has('errors'))
<p class="text-danger">
  <i class="fa fa-exclamation" aria-hidden="true"></i>{{ Session::get('errors') }}
</p>
@endif
<div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"> Tên Người Mua </th>
        <th scope="col"> Tên Sản Phẩm </th>
        <th scope="col"> Số Lượng </th>
        <th scope="col"> Giá Tiền </th>
      </tr>
    </thead>
    <tbody>
      @foreach ($orderdetails as $key => $orderdetail)
      <tr>
        <td>{{ $key+1 }}</td>
        <td>{{ $orderdetail->order->user->name }}</td>
        <td>{{ $orderdetail->product->name }}</td>
        <td>{{ $orderdetail->quantity}}</td>
        <td>{{ number_format($orderdetail->price) }}</td>
        <td>
          <a class="btn btn-info" href="{{ route('orderdetails.edit', $orderdetail->id) }}"><i class="fas fa-edit"></i></a>
          <a class="btn btn-warning" href="{{ route('orderdetails.show', $orderdetail->id) }}"><i class="fas fa-eye"></i></a>
          <form method="post" action="{{ route('orderdetails.destroy', $orderdetail->id) }}" style="display:inline">
            @csrf
            @method('delete')
            <button class="btn btn-danger" type="submit" onclick="return confirm('Bạn chắc chắn muốn xóa?')"> <i class="fas fa-trash-alt"></i></button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <span aria-hidden="true"> {{ $orderdetails->links() }}</span>
    </ul>
  </nav>
</div>
@endsection

casestudy_md3/resources/views/admin/orderdetails/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="container" style="width:600px">
    <h1 class= "text-center">Chi tiết danh sách </h1>
    <div class="card">
        <div class="card-header" style="text-align: center;color:red">Thông tin <b style="color:black">{{ $orderdetails->order->user->name   }}</b></div>
        <div class="card-body">
            <div class="card-body">
                <h5 class="card-title" style="color:red">Tên         : <b style="color:black"> {{ $orderdetails ->order->user->name }} </b> </h5>
                <p class="card-text" style="color:red">Tên Sản Phẩm : <b style="color:black"> {{ $orderdetails->product->name }} </b></p>
                <p class="card-text" style="color:red">Số Lượng     : <b style="color:black"> {{ $orderdetails->quantity }} </b></p>
                <p class="card-text" style="color:red">Giá Tiền     : <b style="color:black"> {{ number_format($orderdetails->price).' VNĐ' }} </b></p>
              
            </div>
            </hr>
        </div>
    </div>
    <div class= "mt-2 text-end">
    <a href="{{route('orderdetails.index')}}" class="btn btn-success"> <i class="fas fa-backward"></i> Quay lại</a>
    </div>
</div>
@endsection 