casestudy_md3/routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\OrderdetailController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HomeUsersController;
use App\Http\Controllers\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('admin1', function () {
    return view('homeadmin');
});
Route::prefix('admin')->group(function () {
    Route::resource('users', UserController::class);
    Route::get('users/search', [UserController::class, 'search'])->name('users.search');

    Route::resource('products', ProductController::class);
    Route::get('products/search', [ProductController::class, 'search'])->name('products.search');

    Route::resource('categories', CategoryController::class);
    Route::get('categories/search', [CategoryController::class, 'search'])->name('categories.search');

    Route::resource('orders', OrderController::class);
    Route::get('orders/search', [OrderController::class, 'search'])->name('orders.search');

    Route::resource('orderdetails', OrderdetailController::class);
    Route::get('orderdetails/search', [OrderdetailController::class, 'search'])->name('orderdetails.search');

   
   
});


Route::prefix('/home')->group(function () {


    Route::get('/home', [HomeController::class, 'home'])->name('home');
    Route::get('/login', [HomeController::class, 'login'])->name('home.login');
    Route::get('/web', [HomeController::class, 'web'])->name('home.web');
    Route::post('/handlelogin', [HomeController::class, 'handlelogin'])->name('home.handlelogin');
    Route::get('/register', [HomeController::class, 'register'])->name('home.register');
    Route::post('/handleRegister', [HomeController::class, 'handleRegister'])->name('home.handleRegister');
    Route::get('/category/{id}', [HomeController::class, 'category'])->name('category');
    Route::get('/detail/{id}', [HomeController::class, 'detail'])->name('detail');
    Route::get('/cart', [HomeController::class, 'cart'])->name('cart');
    Route::post('/addToCart/{id}', [HomeController::class, 'addToCart'])->name('addToCart');
    Route::get('/delete/{id}', [HomeController::class, 'delete'])->name('delete');
});

Route::prefix('/homeUsers')->group(function () {
    Route::get('/category/{id}', [HomeUsersController::class, 'category'])->name('homeUsers.category');
    Route::get('/detail/{id}', [HomeUsersController::class, 'detail'])->name('homeUsers.detail');
    Route::get('/cart', [HomeUsersController::class, 'cart'])->name('homeUsers.cart');
    Route::get('/index', [HomeUsersController::class, 'index'])->name('index');
    Route::post('/addToCartUser/{id}', [HomeUsersController::class, 'addToCartUser'])->name('addToCartUser');
    Route::get('/deleteUser/{id}', [HomeUsersController::class, 'deleteUser'])->name('deleteUser');
});

casestudy_md3/app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\OrdersRequest;
use App\Models\OrderModel;
use App\Models\User;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       
        $search = $request->search;
        
        // mục tìm kiếm 
        if ($search) {
            $orders = OrderModel::where('users_id','like','%'.$search.'%')->paginate(5);
        } else {
            $orders = OrderModel::orderBy('users_id','asc')->paginate(5);
        }
        $params = [
            'orders' => $orders
        ];
        return view ('admin.orders.index',$params );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        return view('admin.orders.create' ,compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrdersRequest $request)
    {   
        $orders                 = new OrderModel();
        $orders->users_id       = $request->users_id;
        $orders->total          = $request->total;
        $orders->order_date     = $request->order_date;
        $orders->status         = $request->status;

        $orders->save();
        Session::flash('success', 'Tạo mới khách hàng thành công');
        //tao moi xong quay ve trang danh sach khach hang
        return redirect()->route('orders.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $orders = OrderModel::find($id);
        return view('admin.orders.show', compact('orders'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = OrderModel::find($id);
        $users = User::all();
        $params = [
            'order' => $order,
            'users' => $users
        ];
        return view('admin.orders.edit' , $params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrdersRequest $request, $id)
    {
        
        OrderModel::find($id)->update($request->only('users_id','total','order_date','status'));
        return redirect()->route('orders.index')->with('success', 'Cập nhật thành công.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            OrderModel::find($id)->delete();
           }
       catch(Exception $e)
           {
               Session::flash('errors','Xóa không thành công');
               return back()->withError('Xóa không thành công')->withInput();
           }
        // OrderModel::find($id)->delete();
        return redirect()->route('orders.index')->with('success', 'Xóa thành công');
    }
}

casestudy_md3/resources/views/admin/orders/create.blade.php
@extends('layouts.admin')
@section('content')

<form method = "post" action = '{{route("orders.store")}}' > 
    @csrf
    <h1 class = "text-center">Thêm Đơn Hàng </h1>
    <div class="container">
    <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Tên người mua :</label>
            <select name = "users_id" class="form-control">
                @foreach ($users as $user)
                <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach 
            </select>
            @if ($errors)
                <div class = "text-danger">{{$errors->first('users_id')}}</div>
            @endif
        </div> 
        
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Tổng tiền: </label>
            <input type="number" class="form-control" id="exampleInputEmail1" name = "total">
            @if ($errors)
                <div class = "text-danger">{{$errors->first('total')}}</div>
            @endif
        </div>
      
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Ngày mua :</label>
            <input type="date" class="form-control" id="exampleInputEmail1" name = "order_date">
            @if ($errors)
                <div class = "text-danger">{{$errors->first('order_date')}}</div>
            @endif
        </div>
        
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label"> Trạng thái: </label>
            <!-- <input type="text" class="form-control" id="exampleInputEmail1" name = "status"> -->
            <select name = "status" class="form-control">
                <option></option>
                <option> Đã thanh toán </option>
                <option> Chưa thanh toán </option>
            </select>
            @if ($errors)
                <div class = "text-danger">{{$errors->first('status')}}</div>
            @endif
        </div>
  
         
        <button type="submit" class="btn btn-primary"><i class="fas fa-user-plus"></i> Thêm</button>
        <a type="submit" class="btn btn-dark" href = "{{ route('products.index') }}"><i class="fas fa-backward"></i> Trở lại</a>
    </div>
</form>

@endsection

casestudy_md3/resources/views/admin/orders/edit.blade.php
@extends('layouts.admin')
@section('content')

<h1 class="text-center">Chỉnh Sửa Đơn Hàng </h1>
<div class="container">
    <div class="mb-3">
        <form method="post" action='{{ route("orders.update", $order->id) }}'>
            @csrf
            @method('put')

            <label for="exampleInputEmail1" class="form-label">Tên người mua</label>
            <select name="users_id" value="{{ $order->users_id }}" class="form-control">
                @foreach ($users as $user)
                <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
            </select>
            @if ($errors)
            <div class="text-danger">{{$errors->first('users_id')}}</div>
            @endif
    </div>

    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Ngày mua </label>
        <input type="date" class="form-control" id="exampleInputEmail1" name="order_date" value="{{ $order->order_date }}">
        @if ($errors)
        <div class="text-danger">{{$errors->first('order_date')}}</div>
        @endif
    </div>

    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Tổng</label>
        <input type="text" class="form-control" id="exampleInputEmail1" name="total" value="{{ $order->total }}">
        @if ($errors)
        <div class="text-danger">{{$errors->first('total')}}</div>
        @endif
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Trạng thái</label>
        <select name="status" value="{{$order->status}}" class="form-control">
            <option value=""> </option>
            <option value="Đã thanh toán"> Đã thanh toán </option>
            <option value="Chưa thanh toán"> Chưa thanh toán</option>
        </select>

        @if ($errors)
        <div class="text-danger">{{$errors->first('status')}}</div>
        @endif
    </div>


    <button type="submit" class="btn btn-primary"><i class="fas fa-pencil-alt"></i>  Chỉnh sửa</button>
    <a type="submit" class="btn btn-dark" href="{{ route('orders.index') }}"> <i class="fas fa-backward"></i> Trở lại</a>
</div>
</form>

@endsection

casestudy_md3/resources/views/admin/orders/index.blade.php
@extends('layouts.admin')

@section('content')
<h1 class="text-center">  Danh Sách Đơn Hàng </h1>

<a class="btn btn-success" href="{{route('orders.create')}}"><i class="fas fa-folder-plus"></i>Thêm</a>
@if (Session::has('success'))
<p class="text-success">
  <i class="fa fa-check" aria-hidden="true"></i>{{ Session::get('success') }}
</p>
@endif
@if (Session::has('errors'))
<p class="text-danger">
  <i class="fa fa-exclamation" aria-hidden="true"></i>{{ Session::get('errors') }}
</p>
@endif
<div>
  <table class="table table-striped">
    <thead>
      <tr>
       
        <th scope="col">#</th>
        <th scope="col"> Tên Người Mua </th>
        <th scope="col"> Ngày Mua </th>
        <th scope="col"> Tổng Tiền </th>
        <th scope="col"> Trạng Thái </th>
        <th scope="col"> Hành động </th>
      </tr>
    </thead>
    <tbody>
      @foreach ($orders as $key => $order)
      <tr>
        <td>{{ $key+1 }}</td>
        <td>{{ $order->user->name }}</td>
        <td>{{ $order->order_date }}</td>
        <td>{{ number_format($order->total) }}</td>
        <td>{{ $order->status}}</td>
        <td>
          <a class="btn btn-info" href="{{ route('orders.edit', $order->id) }}"><i class="fas fa-edit"></i></a>
          <a class="btn btn-warning" href="{{ route('orders.show', $order->id) }}"><i class="fas fa-eye"></i></a>
          <form method="post" action="{{ route('orders.destroy', $order->id) }}"  style="display:inline">
            @csrf
            @method('delete')
            <button class="btn btn-danger" type="submit" onclick="return confirm('Bạn chắc chắn muốn xóa?')"> <i class="fas fa-trash-alt"></i></button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <span aria-hidden="true"> {{ $orders->links() }}</span>
    </ul>
  </nav>
</div>
@endsection

casestudy_md3/resources/views/admin/orders/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="container" style="width:600px">
    <h1 class="text-center">Chi tiết đơn hàng</h1>
    <div class="card">
        <div class="card-header" style="text-align: center;color:red">Thông tin <b style="color:black">{{ $orders->user->name}}</b></div>
        <div class="card-body">
            <div class="card-body">
                <h5 class="card-title" style="color:red">Tên : <b style="color:black"> {{ $orders->user->name }} </b> </h5>
                <p class="card-text" style="color:red"> Tổng tiền: <b style="color:black"> {{number_format($orders->total).' VNĐ'}} </b></p>
                <p class="card-text" style="color:red"> Ngày mua : <b style="color:black"> {{ $orders->order_date  }} </b></p>
                <p class="card-text" style="color:red">Trạng thái : <b style="color:black"> {{ $orders->status }} </b></p>
            </div>
            </hr>
        </div>
    </div>
    <div class="mt-2 text-end">
        <a href="{{route('orders.index')}}" class="btn btn-success"> <i class="fas fa-backward"></i> Quay lại</a>
    </div>
</div>
@endsection